DNWb/Controllers/BulkyBooksController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Bulky.Models;
using Bulky.DataAccess.Repo.IRepo;
using Microsoft.AspNetCore.Authorization;

namespace DNWb.Controllers
{
    [Authorize]
    public class BulkyBooksController : Controller
    {

        public readonly IUnitOfWork _logger;
        public BulkyBooksController(IUnitOfWork logger)
        {
            _logger = logger;

        }
        // GET: BulkyBooksController
        public ActionResult Index()
        {
            IEnumerable<BulkyBook> res = _logger.bulkybooks.GetAll().ToList();
         
            return View(res);
        }

        // GET: BulkyBooksController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: BulkyBooksController/Create
        [Authorize(Roles ="admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: BulkyBooksController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BulkyBook model)
        {
            if (ModelState.IsValid)
            {
                _logger.bulkybooks.Add(model);
                _logger.Save();
            }
            ModelState.Clear();

            return View();
        }

        // GET: BulkyBooksController/Edit/5 
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: BulkyBooksController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: BulkyBooksController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: BulkyBooksController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

DNWb/Controllers/CategoryController.cs
using Bulky.DataAccess.Data;
using Bulky.Models;
using Microsoft.AspNetCore.Mvc;
using Bulky.DataAccess.Repo.IRepo;

namespace DNWb.Controllers
{
    public class CategoryController : Controller
    {
       // public readonly ApplicationDbContext _db;

      //  public readonly ICategory _db;
         public readonly IUnitOfWork _db;
        public CategoryController(IUnitOfWork db)
        {
            _db = db;

        }
        public IActionResult Index()
        {
           // IEnumerable<Category> objCategoryList = _db.Categories.ToList();
           IEnumerable<Category> objCategoryList = _db.category.GetAll().ToList();
            return View(objCategoryList);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category obj)
        {
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("Customerror", "The Display Order and Name can't be the same");
            }
            if (ModelState.IsValid)
            {
                _db.category.Add(obj);
                _db.Save();
                TempData["success"] = "Category created successfully";
                return RedirectToAction("Index");
            };
            return View(obj);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Category? categoryfromDb = _db.category.Get(x=>x.Id==id);
            //Category? categoryfromDb = _db.Categories.FirstOrDefault(id)
            //Category? categoryfromDb = _db.Categories.SingleOrDefault(id)
            if (categoryfromDb == null)
            {
                return NotFound();
            }
            return View(categoryfromDb);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category obj)
        {
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("Customerror", "The Display Order and Name can't be the same");
            }
            if (ModelState.IsValid)
            {
                _db.category.Update(obj);
                _db.Save();
                TempData["success"] = "Category updated successfully";
                return RedirectToAction("Index");
            };
            return View(obj);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
          //  Category? categoryfromDb = _db.Categories.Find(id);
            Category? categoryfromDb = _db.category.Get(x => x.Id == id);
            if (categoryfromDb == null)
            {
                return NotFound();
            }
            return View(categoryfromDb);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.category.Get(x => x.Id == id);
            if (obj == null)
            {
                return NotFound();
            }

           // _db.Categories.Remove(obj);
            _db.category.Remove(obj);
            _db.Save();
            TempData["success"] = "Category Deleted successfully";
            return RedirectToAction("Index");


        }
        public ActionResult Demo()
        {
           List<DemoModel> dm = new List<DemoModel>(){ 
            new DemoModel()
            {
                Id=1,
                Name="ljlj",
                Description=new String[]{"ljds1","ouue1","sfs"}
            },
            new DemoModel(){
                Id=2,
                Name="hjvg",
                Description=new String[]{"ljds2","ouue2","ljjsdf"}
            }
            };

            return View(dm);
        }

    }
}

DNWb/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Bulky.Models;

namespace DNWb.Controllers
{
    public class HomeController : Controller
    {
       

        public HomeController()
        {
        }
        public IActionResult Index()
        {
            var x = Index1();
            return View("Index1",x);
        }
      
         

        public List<AllItems> Index1()
        {
            return new List<AllItems>()
            {
                new AllItems()
                {
                    Id = 1,
                    Name="Stationery",
                    Description="lorem ipsum demo demo demo",
                    Img="https://5.imimg.com/data5/XI/PZ/CQ/SELLER-89977312/stationary-goods-500x500.jpeg",
                    TimePass=5
                },
                  new AllItems()
                {
                    Id = 2,
                    Name="Grocery",
                    Description="lorem ipsum demo3 demo demo5",
                    Img="https://5.imimg.com/data5/SELLER/Default/2021/3/KO/QG/XG/3922575/all-grocery-items-500x500.jpg",
                    TimePass=2
                },
                    new AllItems()
                {
                    Id = 3,
                    Name="Bookings",
                    Description="lorem ipsum9 demo demo1 demo",
                    Img="https://www.shutterstock.com/shutterstock/photos/2172252889/display_1500/stock-vector-travel-promo-vector-design-travel-tour-text-with-special-offer-discount-with-airplane-and-location-2172252889.jpg",
                    TimePass=4
                }
            };
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DNWb/Views/Home/Index.cshtml
<div class="text-center">

    <a asp-controller="BulkyBooks" asp-action="Index">bulkybooks</a>
    <a asp-controller="BulkyBooks" asp-action="Create">Register book</a>
    <a asp-controller="Category" asp-action="Demo">Demo</a>
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DNWb/Views/Home/Index1.cshtml
@model IEnumerable<Bulky.Models.AllItems>
@using Bulky.Models;

@{
    ViewData["Title"] = "Index1";
}

<h1>Index1</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
@*<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Img)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TimePass)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if(Model != null)
        {
            @foreach (var item in Model)
             {
                 <div class="d-flex flex-row">
                     <div>
                        @Html.DisplayFor(modelItem => item.Id)
                        @Html.DisplayFor(modelItem => item.Name)
                        @Html.DisplayFor(modelItem => item.Description) 
                        @Html.DisplayFor(modelItem => item.Img)
                        @Html.DisplayFor(modelItem => item.TimePass)
                     </div>
                </div>
               @* <tr>
                    <td>
                            @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                            @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                            @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                            @Html.DisplayFor(modelItem => item.Img)
                    </td>
                    <td>
                            @Html.DisplayFor(modelItem => item.TimePass)
                    </td>
                    <td>
                            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                    </td>
                </tr>
             
               
            }
        }
      
    </tbody>
</table>*@  
   @* added a new comment here *@
   <h1>vsc</h1>
  @if(Model != null)
        {
    <div class="d-flex flex-row flex-wrap">
            @foreach (var item in Model)
             {

            <div class="border border-0 border-secondary ms-3 mb-3 col-lg-5" style="color:grey;">
                @if (item.Name == "Stationery")
                {
                    <a asp-action="Index" asp-controller="BulkyBooks" style="text-decoration:none">
                        <img src="@Html.DisplayFor(modelItem => item.Img)" alt="img here" height="200" width="460" /> <br />

                        <div class="text-decoration-none" style="padding:15px; line-height:.5;">
                            @Html.DisplayFor(modelItem => item.TimePass) m  <br />
                            <h3> @Html.DisplayFor(modelItem => item.Name) </h3>  <br />
                            @Html.DisplayFor(modelItem => item.Description)
                        </div>
                      
                    </a>
                }
                else
                {
                    <a asp-action="#" asp-controller="##" style="text-decoration:none">
                        <img src="@Html.DisplayFor(modelItem => item.Img)" alt="img here" height="200" width="460" /> <br />
                        <div class="text-decoration-none"  style="padding:15px; line-height:.5">
                            @Html.DisplayFor(modelItem => item.TimePass) m  <br />
                            <h3> @Html.DisplayFor(modelItem => item.Name) </h3>  <br />
                            @Html.DisplayFor(modelItem => item.Description)
                        </div>
                    </a>
                }

                     </div>
         
        }
    </div>
             }