dotnetcore7b/Controllers/AccessController.cs
using Bulky.DataAccess.Repo.IRepo;
using Bulky.Models;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;


namespace DNW.Controllers
{
    public class AccessController : Controller
    {
        public readonly IUnitOfWork _db;
        public AccessController(IUnitOfWork db)
        {
            _db = db;
        }

        public IActionResult LogIn()
        {

               
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> LogIn(UserModel usr)
        {
            bool isValid = _db.userModel.GetAll().Any(x => x.UserName == usr.UserName && x.Password == usr.Password);

            if (isValid)
            {
                List<Claim> cl = new List<Claim>()
                {
                    new Claim(ClaimTypes.NameIdentifier, usr.UserName),
                    new Claim("demo", "demo1"),
                };
                ClaimsIdentity clI = new ClaimsIdentity(cl, CookieAuthenticationDefaults.AuthenticationScheme);
                AuthenticationProperties prop = new AuthenticationProperties()
                {
                    AllowRefresh = true,
                   IsPersistent = true
                };
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(clI));
                return RedirectToAction("Index","Home");
            }
            return View();
        }

        public IActionResult SignUp()
        {

            return View();
        }
        [HttpPost]
        public IActionResult SignUp(UserModel usr)
        {
                  _db.userModel.Add(usr);
                  _db.Save();
           
                return RedirectToAction("LogIn");
            

        }

        public async Task<IActionResult> SignOut(UserModel usr)
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            return RedirectToAction("LogIn");


        }
    }
}

dotnetcore7b/Controllers/CategoryController.cs
using Bulky.DataAccess.Data;
using Bulky.Models;
using Microsoft.AspNetCore.Mvc;
using Bulky.DataAccess.Repo.IRepo;

namespace DNW.Controllers
{
    public class CategoryController : Controller
    {
       // public readonly ApplicationDbContext _db;

      //  public readonly ICategory _db;
         public readonly IUnitOfWork _db;
        public CategoryController(IUnitOfWork db)
        {
            _db = db;

        }
        public IActionResult Index()
        {
           // IEnumerable<Category> objCategoryList = _db.Categories.ToList();
           IEnumerable<Category> objCategoryList = _db.category.GetAll().ToList();
            return View(objCategoryList);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category obj)
        {
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("Customerror", "The Display Order and Name can't be the same");
            }
            if (ModelState.IsValid)
            {
                _db.category.Add(obj);
                _db.Save();
                TempData["success"] = "Category created successfully";
                return RedirectToAction("Index");
            };
            return View(obj);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Category? categoryfromDb = _db.category.Get(x=>x.Id==id);
            //Category? categoryfromDb = _db.Categories.FirstOrDefault(id)
            //Category? categoryfromDb = _db.Categories.SingleOrDefault(id)
            if (categoryfromDb == null)
            {
                return NotFound();
            }
            return View(categoryfromDb);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category obj)
        {
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("Customerror", "The Display Order and Name can't be the same");
            }
            if (ModelState.IsValid)
            {
                _db.category.Update(obj);
                _db.Save();
                TempData["success"] = "Category updated successfully";
                return RedirectToAction("Index");
            };
            return View(obj);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
          //  Category? categoryfromDb = _db.Categories.Find(id);
            Category? categoryfromDb = _db.category.Get(x => x.Id == id);
            if (categoryfromDb == null)
            {
                return NotFound();
            }
            return View(categoryfromDb);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.category.Get(x => x.Id == id);
            if (obj == null)
            {
                return NotFound();
            }

           // _db.Categories.Remove(obj);
            _db.category.Remove(obj);
            _db.Save();
            TempData["success"] = "Category Deleted successfully";
            return RedirectToAction("Index");


        }
        public ActionResult Demo()
        {
           List<DemoModel> dm = new List<DemoModel>(){ 
            new DemoModel()
            {
                Id=1,
                Name="ljlj",
                Description=new String[]{"ljds1","ouue1","sfs"}
            },
            new DemoModel(){
                Id=2,
                Name="hjvg",
                Description=new String[]{"ljds2","ouue2","ljjsdf"}
            }
            };

            return View(dm);
        }

    }
}

dotnetcore7b/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DNW</title>
    <link rel="stylesheet" href="~/css/bootstraptheme.css" />
    
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/BulkyBook.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="~/DNW.styles.css" asp-append-version="true" />
</head>
<body>
   
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#"> <h3>DNW</h3></h3></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home  </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                     
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-sm-2" type="search" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                    <ul class="navbar-nav ml-auto">
                        @if(User.Identity.IsAuthenticated){
                             <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Access" asp-action="SignOut">Logout</a>
                        </li>
                        } else{
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Access" asp-action="LogIn">Login  @ViewBag.name</a>
                            </li>
                           
                        }
                       
                         
                        </ul>
                </div>
            </div>
        </nav>
     
        
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
          
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - DNW - <a asp-area="" asp-controller="Home" asp-action="Privacy"> Privacy </a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

dotnetcore7b/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js" ></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<script type="text/javascript">
    toastr.success('@TempData["success"]');
</script>
   
}
@if (TempData["error"] != null)
{

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<script type="text/javascript">
    toastr.error('@TempData["error"]');
</script>
  
}